model: fff.FiberModel

val_every_n_epoch: 5
compute_c_on_fly: True
noise: 0.002
ae_conditional: False
load_subject_model: True
latent_distribution:
  name: "normal"
data_set:
  name: ldct
  root: /home/hd/hd_hd/hd_gu452/ldct_data
  # root: /mnt/SSD_2TB/ldct_data
  condition: lowdose
  data: highdose
  patchsize: 512
  resize_to: 224
  subject_model_type: PrecompiledModel
  subject_model_path: notebooks/SubjectModels/saved_models/BiomedClip.pt
  augment: True

eval_all: True
loss_weights:
  ae_elbo: 0.00001
  ae_noisy_l1_reconstruction: 10
  ae_perceptual_loss: 1

sm_input_transform: normalize_ct_image
  
max_epochs: 500

train_lossless_ae: True
vae: True
lossless_ae:
  model_spec:
    - name: fff.model.LDCTInvModel
      latent_dim: 3920
      ch_factor: 48
      latent_image: True
  use_condition_decoder: True

gradient_clip: 1.0

density_model:
  - name: fff.model.Identity

lr_scheduler: "onecyclelr"
optimizer:
  name: adam
  lr: 0.0005

batch_size: 64
# batch_size: 2

num_workers: 8

model_checkpoint:
  monitor: auto
  save_last: true
